### ISSUE TITLE
User Genres have different IDs than Official Genres

### ISSUE THREAD

**Issue by afmartin** [MrMagaw/CMPT305---SteamWeb#2]
This is holding back the pull request.  Since we will end up having duplicated user genres object.  There were a few possible ways to fix it:
- Do we need ID of the genres?  If we just go by the name of genre only then there is no problem.
- If we need it I could either add a user_genre field.  Set ID to official genre ID if exists, otherwise set it to zero.

Thoughts?

**Comment by MrMagaw** [comment]
We could cut out the id of the genre, and reference it all by the name, but this would require doing some sleuthing around the code, as I reference genre by id everywhere I use it (including the game cache). In addition to that, adding a user_genre boolean might be beneficial in case we ever want to strip either the user genre or steam genre's out.
