### ISSUE TITLE
Total time seems to always be 0

### ISSUE THREAD

**Issue by afmartin** [MrMagaw/CMPT305---SteamWeb#6]
Not sure what's happening but I noticed lately in stdout (make sure to check log as it hooks stdout/stderr) that often the percentages will be Infinity and total time will be zero.  Just making this as a note, a bit too tired to find out why tonight.

**Comment by MrMagaw** [comment]
I believe that happens when someone has no games.

**Comment by afmartin** [comment]
it happened when I added any vanity that does have games.
